### ISSUE TITLE
Provide meaningful help messages for OAuth 2.0 configuration

### ISSUE THREAD

**Issue by ilgrosso** [jenkinsci/azure-slave-plugin#11]
The new OAuth 2.0 configuration fields introduced for authenticating with ARM are not yet documented:
 * nativeClientId
 * oauth2TokenEndpoint
 * azureUsername
 * azurePassword

**Comment by fmartelli** [comment]
Provided by 
d5653cf55c8d559ed90abe107dc1948602dbeb1b
749be4c07b01d572a8ae4df1add49cb8dabba0d9
