### ISSUE TITLE
Is the plugin still maintained?

### ISSUE THREAD

**Issue by Jaykah** [jenkinsci/azure-slave-plugin#14]
There are a few critical issues described in Jenkins JIRA, so I was wondering if there are any active maintainers since it is no longer usable with the latest Jenkins version.

https://issues.jenkins-ci.org/browse/JENKINS-30014?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27azure-slave-plugin%27

**Comment by snallami** [comment]
@Jaykah, Thanks for reporting. 
I will fix this issue in coming week

**Comment by snallami** [comment]
@Jaykah , i made couple of changes in cloud retention strategy and i also kept it simple without retry strategies. 

https://github.com/jenkinsci/azure-slave-plugin/commit/2db0787c4afa01830ea3f9fc9b770e742400e154

Please update JIRA if you are still seeing issue after release. I am planning to release the plugin on Jan 14th or 15th.
