### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by drorasaf** [jenkinsci/azure-slave-plugin#41]
When does the azure slave plugin will be available as is in the jenkins plugins repository?
Are there any instructions to use it meantime?

**Comment by rtyler** [comment]
@drorasaf I'm not sure what the plans here are, but @bbenz told me at Jenkins World about a new Jenkins plugin Microsoft has developed which would be built on ARM.

I wonder if @mmitche knows anything about it :smiling_imp:

**Comment by arroyc** [comment]
We are testing the ARM plugin and making things better, it's in ARM-dev branch, you can checkout the code and build the hpi and install locally, we will make it available as soon as we are done with testing

**Comment by rtyler** [comment]
@arroyc would that be configuration-compatible with existing "Cloud" configurations in Jenkins? If not is there any migration process/strategy for getting configurations from the older format to a newer one?

**Comment by arroyc** [comment]
when you say configuration-compatible do you mean using existing "Cloud" configuration in the new ARM plugin? That's not going to happen unfortunately, but new configuration is way easier and gives more control to the developer, you have to set your AD secrets in the portal and use it. Everything will be well documented with examples.

**Comment by mmitche** [comment]
@rtyler The new configuration isn't quite compatible with the old one.  However, we may be able to ensure that the old and new are available side by side so that you can transition from one to the other.

**Comment by rtyler** [comment]
> The new configuration isn't quite compatible with the old one. However, we may be able to ensure that the old and new are available side by side so that you can transition from one to the other.

That's a reasonable middle ground to me. I understand that fundamentally different resources would be used underneath the covers. From a practical standpoint, I cannot migrate to an ARM-based version if it would obliterate all my existing configuration, so having both makes migration possible.

**Comment by mmitche** [comment]
right.  you can run multiple clouds at once, so it would be a matter of migrating templates one at a time and verifying.  Most settings are the same but a good number are not.
