### ISSUE TITLE
ARM: Init script execution waits for password

### ISSUE THREAD

**Issue by mmitche** [jenkinsci/azure-slave-plugin#52]
ssh tty not enabled by default for Ubuntu at least.  Worked in old plugin.  Maybe image just needs to be updated?

**Comment by arroyc** [comment]
@mmitche  Does it still hapen? Whats the way to repro?

**Comment by mmitche** [comment]
@arroyc Nope, this was a race condition I resolved before the initial merge of my PR into ARM-dev
