### ISSUE TITLE
ARM version should use the credentials plugin

### ISSUE THREAD

**Issue by rtyler** [jenkinsci/azure-slave-plugin#56]
I noticed [this code](https://github.com/jenkinsci/azure-slave-plugin/blob/master/src/main/java/com/microsoftopentechnologies/azure/ServiceDelegateHelper.java#L92-L93) when I experienced issues with Jenkins inside of a Docker container.

It appears that the legacy version of the plugin is improperly storing credentials in a computed path. Instead the plugin should use more recent credentials storage best practices via the 'credentials' APIs.

**Comment by arroyc** [comment]
thanks @rtyler , will look into it

**Comment by clguimanMSFT** [comment]
This was fixed in ARM-dev
