### ISSUE TITLE
Q: default slave init script?

### ISSUE THREAD

**Issue by ishepherd** [jenkinsci/azure-slave-plugin#60]
From plugin config settings:

> Help for feature: Init Script
> Ensure image is pre-configured with a Java runtime or provide a script to install Java in headless (silent) mode. If using JNLP, you can leave this blank for default script to execute or refer [here](https://gist.github.com/snallami/5aa9ea2c57836a3b3635) for a sample script.

Thanks for the sample.
1. Am I right that this [DEFAULT_INIT_SCRIPT](https://github.com/jenkinsci/azure-slave-plugin/blob/1afc7ec2c1cd58cf7f016b92daa9642d9fc44197/src/main/java/com/microsoftopentechnologies/azure/util/AzureUtil.java)  is the default? 
2. Maybe link to this from that help message. I am happy with default just want one change. Probably others in the same position.

**Comment by arroyc** [comment]
@ishepherd  are you looking to change it in Master branch or ARM-DEV branch?

**Comment by ishepherd** [comment]
@arroyc It's a help-improvement request.
I had to dig around in the codebase to find what the default init script did. I figured it would be helpful to link to it from that help message.

**Comment by arroyc** [comment]
@ishepherd  that's fine .. thank you .. what I meant in my previous comment is if you want to send a PR send it against ARM-DEV branch (which is latest)
We are not working anything in Master branch (old/classic slave plugin)

**Comment by ishepherd** [comment]
Thanks @arroyc for tip that master is not latest! I see the changes to this script are minimal.
Not done any open source contribs before, I will come back to this. Thanks.

**Comment by arroyc** [comment]
Thanks @ishepherd  ... we are updating ARM-DEV branch regularly, if you are not sending this change we will include this in our next PR .. keep in touch for latest updates ... thanks !!

**Comment by arroyc** [comment]
@ishepherd  .. closing this for now, feel free to reopen this if you anything.
