### ISSUE TITLE
Configuration is not refreshed before verify and after save

### ISSUE THREAD

**Issue by ilgrosso** [jenkinsci/azure-slave-plugin#9]
Neither before verifying the configuration nor after saving an updated configuration, the OAuth 2.0 token is not refreshed from the internal `Configuration` instance.

**Comment by fmartelli** [comment]
Connection configuration cannot be refreshed for instantiated azure slave nodes only.
By d5653cf55c8d559ed90abe107dc1948602dbeb1b has been provided a mechanism to try out with latest specified slaves' cloud configuration parameters. If the specified cloud of this slave is not found or authentication exception persists then the slave is removed.
